---
- hosts: all
  remote_user: root
  vars_files: /vars/variables.yml
  
  tasks:
    - name: Cloud Formation template using Jinja2
    - template:
          src: /playbooks/awsStack.yml.j2
          dest: /home/Ansible/Documents/MyAws_CF.template
          mode: 0644